Algoritmo "semnome"

Var
// Seção de Declarações das variáveis
V1: real
V2: real
media: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o valor da porcentagem do aumento:")
leia(V1)
escreval("Digite o valor do seu salário atual:")
leia(v2)
media <- (V1*V2) /100
escreval ("O valor do seu novo salário é: ", media+V2)
fimescolha

Fimalgoritmo