Algoritmo "semnome"

Var
contador: inteiro
numero:inteiro
Inicio
escreval("Digite um número para o cálculo da tabuada:")
leia(numero)
se (numero <= 10) entao

escreval("============================================")
para contador de 1 ate 10 faca
escreva(contador,"x", numero, "=")
escreval(contador*numero)
fimpara
senao(numero>10) entao
escreval("Seu número está incorreto!")
fimse

Fimalgoritmo