Algoritmo "semnome"

Var

nVetor: vetor [1..3] de inteiro
conta: inteiro

Inicio

    para conta de 1 ate 3 faca
       escreval("Digite o", conta, "º número para vetor.")
         leia(nVetor[conta])
    fimpara
    
    limpatela()
    
       escreval("Na posição 1 o valor é igual a : ", nVetor[1])
       escreval("Na posição 2 o valor é igual a : ", nVetor[2])
       escreval("Na posição 3 o valor é igual a : ", nVetor[3])

Fimalgoritmo