Algoritmo "semnome"

Var

nVetor: vetor [0..3] de caractere
n0, n1, n2, n3 : caractere

Inicio

    escreval ("Digite o primeiro nome:")
      leia(nVetor[0])
    escreval ("Digite o segundo nome:")
      leia(nVetor[1])
    escreval ("Digite o terceiro nome:")
      leia(nVetor[2])


    escreval("O primeiro nome é: ", nVetor[0])
    escreval("O segundo nome é: ", nVetor[1])
    escreval("O terceiro nome é: ", nVetor[2])


Fimalgoritmo